### PR TITLE
Added validation statistics collector

### LINKED ISSUE #81: Add Hovmoeller and daytime means computation
This is a reminder for me (@carloshorn) to add these computations and plotting scripts.

### PR DESCRIPTION
**Pull request by carloshorn**
This PR adds a script to collect statistics for the FDR validation.
It closes #81 by collecting data for Hovmoeller plots and zonal (day, night, twilight) mean values.

### CODE REVIEW

**Comment by carloshorn** [comment]
@sfinkens, I could also add the script to create the plots. Should I also put them into `./bin/` or should they have their own directory? I could also produce the plots at the end of the data collection script. What do you think?

**Comment by sfinkens** [comment]
Nice, thanks a lot @carloshorn ! Sure, the plotting script would be nice to have, too! And I think two steps for collecting and plotting is good. Put them both in `bin` :+1:

**Comment by carloshorn** [comment]
I added the plotting script, but I am not a big fan of it... In my experience, plotting is something interactive, because it usually requires some fine tuning to get the desired results. Furthermore, the user may frequently want to change the plots, e.g. when preparing a presentation or using a different text font, or changing the output format for using it in latex, etc... Therefore, I usually use jupyter notebooks to do these things.
At the same time, I do not want to put a jupyter notebook into this repository, because they are not as static as a script or a module. Maybe, I can separate the data collection and preparation from the actual plotting and leave the plotting itself to the user. 
What do you think @sfinkens?

**Comment by sfinkens** [comment]
I think the collection part is separated very nicely into script and library. And I agree that plotting scripts are never nice. But I think it's good to have it included, if only as a starting point for future activities. What if we place the Jupyter notebook in a `tools` directory? Then it's clear that it's meant for interactive usage. I think the backwards compatibility is pretty good. There are some very old notebooks in pytroll-examples and they still work.

**Comment by sfinkens** [comment]
Without the figures of course :slightly_smiling_face:

**Pull request merged**
