### PR TITLE
Fix DataID access

### LINKED ISSUE #110: DataID name property issue when processing AVHRR tarball
We were recently trying to process a monthly tarball of AVHRR granules using pygac-fdr.  An issue arose where there was an error from the Writer.  We tracked this down to the '_get_encoding' section of the NetcdfWriter. 

Line 363 of writer.py is: 
```
scn_keys = set([key.name for key in scene.keys()]) 
```
which fails as the 'DataID' does not have a .name property.  I think this is because of the dictionary form of DataID.  

We are now doing test runs with a fix where the line is edited to:
```
try:
    scn_keys = set([key.name for key in scene.keys()]) 
else:
    scn_keys = set([key['name'] for key in scene.keys()]) 
```
which seems to be working for now.

### PR DESCRIPTION
**Pull request by sfinkens**
Closes #110 . Also needed minor changes to adapt to the latest Pandas version.

### CODE REVIEW

**Comment by djhoese** [comment]
https://github.com/pytroll/satpy/blob/main/.github/dependabot.yml ?

**Comment by sfinkens** [comment]
I would create separate PRs for adding dependabot and dropping Python-3.8 support.

**Comment by sfinkens** [comment]
Ah no, that doesn't work because tests would fail. So everything in this PR...

**Review by mraspaud — APPROVED** [review]
Lgtm!

**Pull request merged**
